[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false

[etherscan]
arbitrum = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_fork = "${ARBITRUM_RPC_URL}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = true
